all:
  children:
    loadbalancer:
      hosts:
        lb-01:
          ansible_host: 20.24.192.173
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    workers:
      hosts:
        worker-master:
          ansible_host: 10.0.1.5
        worker-slave:
          ansible_host: 10.0.1.4
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyJump=azureuser@20.24.192.173 -o ServerAliveInterval=30 -o ConnectTimeout=30'

  vars:
    ansible_user: azureuser
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
