all:
  children:
    loadbalancer:
      hosts:
        lb-01:
          ansible_host: 20.24.192.173
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    frontend_workers:
      hosts:
        frontend-01:
          ansible_host: 10.0.1.5
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyJump=azureuser@20.24.192.173 -o ServerAliveInterval=30 -o ConnectTimeout=30'

    backend_workers:
      hosts:
        backend-01:
          ansible_host: 10.0.1.4
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyJump=azureuser@20.24.192.173 -o ServerAliveInterval=30 -o ConnectTimeout=30'

    workers:
      children:
        frontend_workers:
        backend_workers:

  vars:
    ansible_user: azureuser
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
